controller_manager:
  ros__parameters:
    update_rate: 100
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:                              
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - magician_joint_1
      - magician_joint_2
      - magician_joint_3
      - magician_joint_4         # <--- AGRÉGALO AQUÍ
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_integration_in_goal_trajectory: true

gripper_controller:
  ros__parameters:
    joints:
      - magician_joint_prismatic_l
      - magician_joint_prismatic_r    # <--- DEJA SÓLO LOS PRISMÁTICOS AQUÍ
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_integration_in_goal_trajectory: true